### ISSUE TITLE
日志组件死锁

### ISSUE THREAD

**Issue by 88250** [88250/gulu#3]
```
goroutine 585 [semacquire, 4 minutes]:
sync.runtime_SemacquireMutex(0xc0001371d4, 0x0)
	D:/go/src/runtime/sema.go:71 +0x44
sync.(*Mutex).Lock(0xc0001371d0)
	D:/go/src/sync/mutex.go:134 +0x110
log.(*Logger).SetPrefix(0xc0001371d0, 0xadcdad, 0x2)
	D:/go/src/log/log.go:252 +0x38
github.com/88250/gulu.(*Logger).Debug(0xc000253590, 0xc0002e19e0, 0x1, 0x1)
	D:/gogogo/pkg/mod/github.com/88250/gulu@v1.1.0/log.go:138 +0x5f
```

```
syscall.Syscall6(0x7ffe88ec2500, 0x5, 0xa60, 0xc00052a000, 0x1f44, 0xc0000936ac, 0x0, 0x0, 0x0, 0x0, ...)
	D:/go/src/runtime/syscall_windows.go:197 +0xed
syscall.WriteFile(0xa60, 0xc00052a000, 0x1f44, 0x2000, 0xc0000936ac, 0x0, 0xc0003b63c0, 0x4)
	D:/go/src/syscall/zsyscall_windows.go:329 +0xd5
syscall.Write(0xa60, 0xc00052a000, 0x1f44, 0x2000, 0x1f44, 0x0, 0x0)
	D:/go/src/syscall/syscall_windows.go:321 +0x6f
internal/poll.(*FD).Write(0xc0000a0280, 0xc00052a000, 0x1f44, 0x2000, 0x0, 0x0, 0x0)
	D:/go/src/internal/poll/fd_windows.go:680 +0x20a
os.(*File).write(...)
	D:/go/src/os/file_windows.go:224
os.(*File).Write(0xc00009e008, 0xc00052a000, 0x1f44, 0x2000, 0x1f44, 0x0, 0x0)
	D:/go/src/os/file.go:145 +0x77
io.(*multiWriter).Write(0xc000266b20, 0xc00052a000, 0x1f44, 0x2000, 0x1045a60, 0xfd865d, 0x7)
	D:/go/src/io/multi.go:60 +0x8e
log.(*Logger).Output(0xc0001371d0, 0x2, 0xc0001e6000, 0x1f21, 0x0, 0x0)
	D:/go/src/log/log.go:172 +0x205
github.com/88250/gulu.(*Logger).Debugf(0xc000253590, 0xae3877, 0xc, 0xc00037f970, 0x1, 0x1)
	D:/gogogo/pkg/mod/github.com/88250/gulu@v1.1.0/log.go:149 +0xc4
```

**Comment by 88250** [comment]
看来是文件锁导致。
